
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 28 21:52:08 EST 2018
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LAZY = 9;
  public static final int MOD = 14;
  public static final int LT = 23;
  public static final int ELSE = 18;
  public static final int PLUS = 10;
  public static final int RBRACE = 21;
  public static final int RPAREN = 3;
  public static final int THEN = 19;
  public static final int CALL = 8;
  public static final int SEMI = 5;
  public static final int VARIABLE = 28;
  public static final int IF = 17;
  public static final int GT = 24;
  public static final int LBRACE = 20;
  public static final int LPAREN = 2;
  public static final int LE = 25;
  public static final int COMMA = 4;
  public static final int EOF = 0;
  public static final int FUNDEF = 6;
  public static final int DIV = 13;
  public static final int GE = 26;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int LET = 16;
  public static final int PROC = 7;
  public static final int EQ = 22;
  public static final int ASSIGN = 15;
  public static final int INTEGER = 27;
  public static final int MUL = 12;
}

